from .room import Room
import math
import random
import pygame
from . import Definitions
from .Entities.Entity import Entity, AI, Shadow
from .generateImageLayout import generate_image_layout
from .generateTiles import generate_tiles

for entityName in Definitions.ENTITY_NAMES:
    images = Definitions.MODELS[entityName].images
    for variationKey in images:
        Entity.initiate_sprite(entityName+f"-{variationKey}", images[variationKey])

fogOfWarCenterPos = ((Definitions.SCREEN_SIZE[0]-Definitions.FOG_OF_WAR_IMAGE.get_width())/2,
                         (Definitions.SCREEN_SIZE[1]-Definitions.FOG_OF_WAR_IMAGE.get_height())/2)




class Dungeon:
    def __init__(self,
                 x:int,
                 y:int,
                 minRooms:int, 
                 maxRooms:int, 
                 rating:int = 0,
                 loot:int = 0) -> None:
        """
        Initialize A Dungeon Object
        
        Parameters:
            x:
                Stores the x position of the dungeon, NOT USED AT THE MOMENT
            y:
                Stores the y position of the dungeon, NOT USED AT THE MOMENT
            
            minRooms:
                The minimum amount of rooms for the dungeon to generate
            maxRooms:
                The maximum amount of rooms for the dungeon to generate
            
            rating:
                N/A
            loot:
                N/A
                
        Function:
            Represents a dungeon in game.
            Initializes all needed variables.
            Then generates rooms.
            
        Output -> None
        """
        
        self.x = x
        self.y = y
        self.minRooms = minRooms
        self.maxRooms = maxRooms
        self.rooms: dict[tuple[int,int], Room] = {} # Will store the rooms generated by the dungeon
        self.starterRoom = [0,0]
        self.tiles = {}
        self.dungeonLayout = {} # Will hold the pygame surfaces to draw on screen
        self.levels = {}
        self.maxZoneId = 0
        self.player = None
        self.generate_image_layout()
        
    def unlock_room(self, roomCoord):
        if roomCoord in self.rooms:
            locked=self.rooms[roomCoord].locked
            self.rooms[roomCoord].locked = False   
            return locked
        else:
            return False
        
    
    
    def generate_tiles(self):
        return generate_tiles(self)
                    
        
    def generate_image_layout(self):
        return generate_image_layout(self)
    
        
    def get_layers(self,screenSize, pos,loadRadius):
        layers = {}
        a=0
        for layerIndex in self.dungeonLayout:
            layer = self.dungeonLayout[layerIndex]
            layers[layerIndex] = {}
            
            for index in layer:
                layers[layerIndex][index] = pygame.Surface((Definitions.SCREEN_SIZE[0],Definitions.SCREEN_SIZE[1]), pygame.SRCALPHA)
                layers[layerIndex][index].fill((0,0,0,0))
                for ix in range(loadRadius):
                    for iy in range(loadRadius):
                        coord = (ix-loadRadius//2-(pos[0]-1)*7+3, iy-loadRadius//2-(pos[1]-1)*7+3)
                        if (coord[0]//1, coord[1]//1) in layer[index]:
                            
                            x = (ix-loadRadius//2-.5)*Definitions.GRID_SQUARE_WIDTH + Definitions.SCREEN_SIZE[0]/2
                            y = (iy-loadRadius//2-.5)*Definitions.GRID_SQUARE_HEIGHT + Definitions.SCREEN_SIZE[1]/2
                            # .
                            
                            
                            img = layer[index][(coord[0]//1, coord[1]//1)]
                            a+=1
                            
                            
                            layers[layerIndex][index].blit(img, (x,y))
                    
        
                    
                
        return layers
        
      
"""
            
            
            
dung = Dungeon(0,0,15,30,0,0)

for i in range(40):
    
    room = random.choice(list(dung.rooms))
    badGuy = Shadow(room[0]*7+random.randint(0,6),room[1]*7+random.randint(0,6),0,"Shadow",1,10,10,dung,dung.rooms[room],"Frame0",dung.rooms[room].zoneId)
    badGuy.movementType = 0

    

x1,y1 = 1,1

currentRoom = dung.rooms[(0,0)]
loadArea = 7

layers = dung.get_layers(Definitions.SCREEN_SIZE, (x1,y1),loadArea)
screen = pygame.display.set_mode(Definitions.SCREEN_SIZE)
angle = 0
clock = pygame.time.Clock()

moving = False

beenIn = []#




while True:
    deltaTime = clock.tick(200)/1000
    events=pygame.event.get()
    keys = pygame.key.get_pressed()
    
    w,d,s,a = keys[pygame.K_w],keys[pygame.K_d],keys[pygame.K_s],keys[pygame.K_a]
    
    if w and not moving:
        #if "north" in currentRoom.sideRooms:
            currentRoom = currentRoom.sideRooms.get("north", currentRoom)
            
            
            
            y1+=1*deltaTime
            
            layers = dung.get_layers(Definitions.SCREEN_SIZE, (x1,y1),loadArea)
            
            if currentRoom not in beenIn:
                beenIn.append(currentRoom)
        
    if d and not moving:
        #if "east" in currentRoom.sideRooms:
            currentRoom = currentRoom.sideRooms.get("east", currentRoom)
            
            x1-=1*deltaTime
            
            
            layers = dung.get_layers(Definitions.SCREEN_SIZE, (x1,y1),loadArea)
            
            if currentRoom not in beenIn:
                beenIn.append(currentRoom)
    
    if s and not moving:
        #if "south" in currentRoom.sideRooms:
            currentRoom = currentRoom.sideRooms.get("south", currentRoom)
            
            y1-=1*deltaTime
            
            layers = dung.get_layers(Definitions.SCREEN_SIZE, (x1,y1),loadArea)
            
            if currentRoom not in beenIn:
                beenIn.append(currentRoom)
        
    if a and not moving:
       # if "west" in currentRoom.sideRooms:
            currentRoom = currentRoom.sideRooms.get("west", currentRoom)
            
            x1+=1*deltaTime
            
            layers = dung.get_layers(Definitions.SCREEN_SIZE, (x1,y1),loadArea)
            
            if currentRoom not in beenIn:
                beenIn.append(currentRoom)
        
    if (not (w or d or s or a)) and moving:
        moving = False
        
    entityLayers = {}
    for room in dung.rooms:
        x,y = room  
        
        
        distance = ((x - currentRoom.x)**2 + (y - currentRoom.y)**2)**0.5
        
        if distance <= 4:
            roomObj = dung.rooms[room]
            for ai in roomObj.entities:
                ai.playerX = currentRoom.x*7
                ai.playerY = currentRoom.y*7
                ai.update()    
            
            for layer in roomObj.entityLayers:
                entityLayers[layer] = entityLayers.get(layer,[])
                entityLayers[layer].append(roomObj.entityLayers[layer])
                
    

    
    
    pygame.display.set_caption(str(clock.get_fps()))
    
        
    
    #
    
    
    screen.fill((0,0,0))
    
    for id,layerIndex in enumerate(layers):
        print(" ")
        for index in layers[layerIndex]:
            size = currentRoom.screenRoomSize
            modifier = size[1] / Definitions.SCREEN_SIZE[1]
            layer = layers[layerIndex][index]
            
            screen.blit(layer, (Definitions.SCREEN_SIZE[0]//2-layer.get_width()/2+(-index-layerIndex)/8,Definitions.SCREEN_SIZE[1]//2-layer.get_height()/2+(-index-layerIndex)))

            
            Zvalue = index+layerIndex+id
            
            if Zvalue in entityLayers:
                for entitys in entityLayers[Zvalue]:
                    for entity in entitys:
                        
                        x,y = entity.x, entity.y
                        
                        drawCoord = (x+.5+int(x1*7))*Definitions.GRID_SQUARE_WIDTH,(y+.5+int(y1*7))*Definitions.GRID_SQUARE_HEIGHT
                        print((x))
                        
                        screen.blit(Definitions.MODELS[entity.spriteName].images[entity.frame][Zvalue-(Definitions.FLOOR_HEIGHT + 1)],drawCoord)
                        
                        
                    
            
                    print(" ")
                    
    for room in dung.rooms:
        x,y = room
        
        
        colour = (255,255,255)
        
        if dung.rooms[room] != currentRoom:
            if dung.rooms[room].locked:
                colour = (165,165,165)
            
            else:
                if dung.rooms[room] not in beenIn:
                    colour = (int(255/dung.maxZoneId*dung.rooms[room].zoneId),0,0)
                else:
                    colour = (0,0,255)
            
            colour = (int(255/dung.maxZoneId*dung.rooms[room].zoneId),0,0)
        else:
            colour = (0,255,0)
            
        pygame.draw.circle(screen, colour, (x*10+currentRoom.screenRoomSize[0]//2, y*10+currentRoom.screenRoomSize[1]//2), 5)
    
                
            
    
    #screen.blit(Definitions.FOG_OF_WAR_IMAGE,fogOfWarCenterPos)
    pygame.display.update()"""